project_name: release-testing
# before:
#   hooks:
#     - go mod tidy

builds:
  - binary: release-testing
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # ignore:
    #   - goos: windows
    #     goarch: arm
    #   - goos: windows
    #     goarch: arm64
    env:
      - CGO_ENABLED=0
    # flags:
    #   - -mod=vendor
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - '{{ .ProjectName }}'  # Include only the binary file
#     replacements:
#       darwin: Darwin
#       linux: Linux
#       windows: Windows
#       amd64: x86_64
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
  
release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
