project_name: release-testing
# before:
#   hooks:
#     - go mod tidy

builds:
  - binary: release-testing
    goos:
      # - darwin
      - linux
      # - windows
    goarch:
      - amd64
      # - arm64
    # ignore:
    #   - goos: windows
    #     goarch: arm
    #   - goos: windows
    #     goarch: arm64
    env:
      - CGO_ENABLED=0
    # flags:
    #   - -mod=vendor
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - "README.md" #'{{ .ProjectName }}'  # Include only the binary file
#     replacements:
#       darwin: Darwin
#       linux: Linux
#       windows: Windows
#       amd64: x86_64
# snapshot:
#   name_template: SNAPSHOT-{{ .Commit }}
  
checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: xfab-hari
    name: Hari
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Features

    List of newly introduced features:

    - Item 1
    - Item 2

    ## Bug fixes

    List of fixed issues:

    - Item 1
    - Item 2

    ## Code changes

    - Item 1
    - Item 2
  footer: |
    ## Thanks!