builds:
  - binary: askcloudhelloworld
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    # flags:
    #   - -mod=vendor

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
