project_name: xfab
before:
  hooks:
    - go mod tidy

builds:
  - binary: release-testing
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # ignore:
    #   - goos: windows
    #     goarch: arm
    #   - goos: windows
    #     goarch: arm64
    env:
      - CGO_ENABLED=0

source:
  enabled: false

archives:
  - format: tar.gz
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows
        format: zip
    files:
      - docs/*
      - README.md
      - backend/config/*
      - RELEASE_NOTES.md


# archives:
#   - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
#     builds:
#       - binary : release-testing
#     files:
#       - none*

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  header: |
    ## Features

    List of newly introduced features:

    - Item 1
    - Item 2

    ## Bug fixes

    List of fixed issues:

    - Item 1
    - Item 2

    ## Code changes

    - Item 1
    - Item 2