project_name: release-testing
# before:
#   hooks:
#     - go mod tidy

builds:
  - binary: release-testing
    id: release-testing
    goos:
      - darwin
      # - linux
      # - windows
    goarch:
      # - amd64
      - arm64
    # ignore:
    #   - goos: windows
    #     goarch: arm
    #   - goos: windows
    #     goarch: arm64
    env:
      - CGO_ENABLED=0
    # flags:
    #   - -mod=vendor

source:
  # Whether this pipe is enabled or not.
  enabled: false
  files:
    - none


archives:
  - build: release-testing
    format: tar.gz
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows
        format: zip
    files:
      - docs/*


# archives:
#   - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
#     builds:
#       - binary : release-testing
#     files:
#       - none*

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  header: |
    ## Features

    List of newly introduced features:

    - Item 1
    - Item 2

    ## Bug fixes

    List of fixed issues:

    - Item 1
    - Item 2

    ## Code changes

    - Item 1
    - Item 2
  footer: |
    ## Thanks!