project_name: xfab-observability-cli
before:
  hooks:
    - go mod tidy

builds:
  - binary: xfab
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

source:
  enabled: false

archives:
  - format: tar.gz
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows
        format: zip
    files:
      - docs/*
      - README.md
      - RELEASE_NOTES.md
      - backend/config/*

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  header: |
    $(cat RELEASE_NOTES.md)
  footer: |
    #### Made with ❤️ by the xFAB team
  footer: |
    #### Made with ❤️ by the xFAB team
