project_name: xfab-observability-cli

builds:
  - binary: xfab
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./backend/


dockers:
  # Build for linux/amd64
  - image_templates:
      - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  # Build for linux/arm64
  - image_templates:
      - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64
  # Build for windows/amd64
  - image_templates:
      - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-windows-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=windows/amd64"
    goos: windows
    goarch: amd64
  # Build for windows/arm64
  - image_templates:
      - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-windows-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=windows/arm64"
    goos: windows
    goarch: arm64

# docker_manifests:
#   - name_template: "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}"
#     image_templates:
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-amd64"
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-arm64"
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-windows-amd64"
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-windows-arm64"


# dockers:
  # - image_templates:
  #     - "ghcr.io/xfab-hari/:{{ .Tag }}-amd64"
  #   use: buildx
  #   build_flag_templates:
  #     - "--pull"
  #     - "--platform=linux/amd64"
  # - image_templates:
  #     - "ghcr.io/xfab-hari:{{ .Tag }}-arm64"
  #   use: buildx
  #   build_flag_templates:
  #     - "--pull"
  #     - "--platform=linux/arm64"
  #   goarch: arm64

  # - use: buildx
  #   goos:
  #     - linux
  #     # - windows
  #   goarch:
  #     - amd64
  #     # - arm64
  #   image_templates:
  #     - "ghcr.io/xfab-hari/:{{ .Tag }}-{{ .Arch }}"
  #   build_flag_templates:
  #     - "pull"
  #     - "--platform={{ .Arch }}"
    # tags:
    #   - ghcr.io/xfab/xfab-observability-cli:latest
    #   - ghcr.io/xfab/xfab-observability-cli:{{.Version}}
    # dockerfile: ./Dockerfile
    # target: backend-builder
    # platform: linux/amd64
    # push: true

source:
  enabled: false

archives:
  - format: tar.gz
    format_overrides: # Which GOOS to override the format for.
      - goos: windows
        format: zip
    files:
      - docs/*
      - CHANGELOG.md
      - backend/config/production.yaml

checksum:
  split: true

release:
  prerelease: auto
  footer: |
    #### Made with ❤️ by the xFab team