project_name: xfab-observability-cli

builds:
  - binary: xfab
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

source:
  enabled: false

archives:
  - format: tar.gz
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows
        format: zip
    files:
      - docs/*
      - README.md
      - RELEASE_NOTES.md
      - backend/config/production.yaml

checksum:
  split: true

release:
  prerelease: auto
  footer: |
    #### Made with ❤️ by the xFab team
