project_name: xfab-observability-cli

builds:
  - binary: xfab
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./backend/


# dockers:
#   # Build for linux/amd64
#   - image_templates:
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-amd64"
#     use: buildx
#     build_flag_templates:
#       - --platform=linux/amd64
#       - --label=org.opencontainers.image.title={{ .ProjectName }}
#       - --label=org.opencontainers.image.description={{ .ProjectName }}
#       - --label=org.opencontainers.image.url=https://github.com/xfab-hari/release-workflow
#       - --label=org.opencontainers.image.source=https://github.com/xfab-hari/release-workflow
#       - --label=org.opencontainers.image.version={{ .Tag }}
#       - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#       - --label=org.opencontainers.image.revision={{ .FullCommit }}
#       - --label=org.opencontainers.image.licenses=MIT

#       # - "--pull"
#       # - "--platform=linux/amd64"
#   # Build for linux/arm64
#   - image_templates:
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-arm64"
#     use: buildx
#     build_flag_templates:
#       - --platform=linux/arm64
#       - --label=org.opencontainers.image.title={{ .ProjectName }}
#       - --label=org.opencontainers.image.description={{ .ProjectName }}
#       - --label=org.opencontainers.image.url=https://github.com/xfab-hari/release-workflow
#       - --label=org.opencontainers.image.source=https://github.com/xfab-hari/release-workflow
#       - --label=org.opencontainers.image.version={{ .Tag }}
#       - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#       - --label=org.opencontainers.image.revision={{ .FullCommit }}
#       - --label=org.opencontainers.image.licenses=MIT
#       # - "--pull"
#       # - "--platform=linux/arm64"
#     goarch: arm64

# docker_manifests:
#   - name_template: "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}"
#     image_templates:
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-amd64"
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-arm64"
#   - name_template: "ghcr.io/xfab-hari/release-workflow:latest"
#     image_templates:
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-amd64"
#       - "ghcr.io/xfab-hari/release-workflow:{{ .Tag }}-arm64"


source:
  enabled: false

archives:
  - format: tar.gz
    format_overrides: # Which GOOS to override the format for.
      - goos: windows
        format: zip
    files:
      - docs/*
      - CHANGELOG.md
      - backend/config/production.yaml

checksum:
  split: true

release:
  prerelease: auto
  footer: |
    #### Made with ❤️ by the xFab team