name: Deploy Images to GHCR

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"
      - "v[0-9].[0-9]+.[0-9]+-[a-z]+.[0-9]+"

permissions:
  contents: read
  packages: write

jobs:
  build-container-images:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Push Backend Image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file Dockerfile \
          --target backend-builder \
          -t ghcr.io/${{ github.repository_owner }}/release-workflow:latest \
          -t ghcr.io/${{ github.repository_owner }}/release-workflow:${{ github.ref_name }} \
          --push .


    # - name: Build and Push Backend Image
    #   run: |
    #     docker buildx build \
    #       --platform linux/amd64 \
    #       --file Dockerfile \
    #       --target backend-builder \
    #       -t ghcr.io/${{ github.repository_owner }}/xfab-backend:latest \
    #       -t ghcr.io/${{ github.repository_owner }}/xfab-backend:${{ github.ref_name }} \
    #       --push .

    # - name: Build and Push Frontend Image
    #   run: |
    #     docker buildx build \
    #       --platform linux/amd64 \
    #       --file Dockerfile \
    #       --target xfab-frontend \
    #       -t ghcr.io/${{ github.repository_owner }}/xfab-frontend:latest \
    #       -t ghcr.io/${{ github.repository_owner }}/xfab-frontend:${{ github.ref_name }} \
    #       --push .
